### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by sbfnk** [VirologyCharite/SARS-CoV-2-VL-paper#1]
Congratulations on this impressive work and getting the paper out.

I've tried to reproduce the analysis by rendering `ExtendedMethods.Rmd` but ran into an error here because the referenced file does not exist in the repo:
https://github.com/VirologyCharite/SARS-CoV-2-VL-paper/blob/3aca779c084c6b61cc7adea0bfaf7dcc6808b112/utils.R#L816

Could this be added?

**Comment by terrycojones** [comment]
Hi Sebastian. Thank you, and thanks for pointing out the omission - sorry for the inconvenience. The file has been added.

**Comment by sbfnk** [comment]
Slowly making my way through the  markdown, it seems to me that

`CP/stan/TC_APGHB117_simple_shiftw25o.stan`

is also missing, referenced here:
https://github.com/VirologyCharite/SARS-CoV-2-VL-paper/blob/cc080de24f4361db904136279b7843c538e5806d/ExtendedMethods.Rmd#L1394

**Comment by gbiele** [comment]
Thanks for pointing this out. The content of this file is in the section "5 Stan model for time course estimation" of the R-markdown, but we'll also upload the file in a moment.

PS: depending on the system you are working on, fitting this model will take a while. 
To fully reproduce the results, the model will be fit with the full data set, and also for people with at least 4, at least 5, ... data points.
